const types = {
  SET_PLAY_STATE: 'SET_PLAY_STATE',
  SET_SELECT_PLAY: 'SET_SELECT_PLAY',
  SET_CURRENT_INDEX: 'SET_CURRENT_INDEX',
  SET_PLAYLIST: 'SET_PLAYLIST',
  SET_PLAY_MODE: 'SET_PLAY_MODE',
  SET_FULL_SCREEN: 'SET_FULL_SCREEN'
}

export default types
