const types = {
  SET_PLAY_STATE: 'SET_PLAY_STATE',
  SET_SELECT_PLAY: 'SET_SELECT_PLAY',
  SET_CURRENT_INDEX: 'SET_CURRENT_INDEX',
  SET_PLAY_LIST: 'SET_PLAY_LIST',
  SET_SEQUENCE_LIST: 'SET_SEQUENCE_LIST',
  SET_PLAY_MODE: 'SET_PLAY_MODE',
  SET_FULL_SCREEN: 'SET_FULL_SCREEN',
  SET_V_KEY: 'SET_V_KEY',
  SET_PLAY_HISTORY: 'SET_PLAY_HISTORY',
  SET_FAVORITE_LIST: 'SET_FAVORITE_LIST'
}

export default types
